steps:
#create archive
- name: 'gcr.io/zortrox-github-builds/ubuntu-common'
  args: ["zip", "-r", "steamchecker_extension.zip", "extension"]

#decrypt
- name: gcr.io/cloud-builders/gcloud
  args: ["kms", "decrypt", "--ciphertext-file=secrets.json.enc", "--plaintext-file=secrets.json", "--location=global", "--keyring=foxslash-apps", "--key=foxslash-key"]

#secret variables
- name: 'gcr.io/zortrox-github-builds/ubuntu-common'
  args: ["bash", "-c", "cat secrets.json | jq -r .clientSecret > _CLIENT_SECRET"]
- name: 'gcr.io/zortrox-github-builds/ubuntu-common'
  args: ["bash", "-c", "cat secrets.json | jq -r .refreshToken > _REFRESH_TOKEN"]
- name: 'gcr.io/zortrox-github-builds/ubuntu-common'
  args: ["bash", "-c", "cat secrets.json | jq -r .jwtSecret > _JWT_SECRET"]

#Chrome Webstore
- name: 'gcr.io/zortrox-github-builds/ubuntu-common'
  args: ["bash", "-c", 'curl https://accounts.google.com/o/oauth2/token -d "client_id=${_CLIENT_ID}&client_secret=$(cat _CLIENT_SECRET)&refresh_token=$(cat _REFRESH_TOKEN)&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token > _ACCESS_TOKEN']
- name: 'gcr.io/zortrox-github-builds/ubuntu-common'
  args: ["bash", "-c", 'curl https://www.googleapis.com/chromewebstore/v1.1/items/${_APP_ID} -H "Authorization: Bearer $(cat _ACCESS_TOKEN)" -H "x-goog-api-version: 2" -X PUT -T steamchecker_extension.zip']
  #curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T pointless.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${_APP_ID}"
- name: 'gcr.io/zortrox-github-builds/ubuntu-common'
  args: ["bash", "-c", 'curl -v https://www.googleapis.com/chromewebstore/v1.1/items/${_APP_ID}/publish -H "Authorization: Bearer $(cat _ACCESS_TOKEN)" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST']
  #curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${_APP_ID}/publish"

#Mozilla Add-ons
- name: 'gcr.io/zortrox-github-builds/ubuntu-common'
  args: ["bash", "-c", "cat test.json | jq -r '.version' > _EXTENSION_VERSION"]
- name: 'gcr.io/zortrox-github-builds/ubuntu-common'
  args: ["bash", "-c", 'curl https://addons.mozilla.org/api/v4/addons/ -g -XPOST -F upload=@steamchecker_extension.zip -F version=$(cat _EXTENSION_VERSION) -H "Authorization: JWT $(cat _JWT_SECRET)"']

artifacts:
  objects:
    location: 'gs://artifacts.zortrox-github-builds.appspot.com/extensions'
    paths: ['steamchecker-extension.zip']

substitutions:
    _CLIENT_ID: 487050059648-4iej3hk4mbbhdravaaake8vs72s2cdi2.apps.googleusercontent.com
    _APP_ID: eopegaefgepfdedhecfbclehhffiebpk

options:
    substitution_option: 'ALLOW_LOOSE'