steps:
#update apt and install zip
- name: 'ubuntu'
  args: ["apt-get", "update", "&&", "apt-get", "install", "-qqy", "zip"]

#create archive
- name: 'ubuntu'
  args: ["zip", "-r", "steamchecker_extension.zip", "extension"]