steps:
#update system
- name: 'ubuntu'
  args: ["apt-get", "update"]
- name: 'ubuntu'
  args: ["apt-get", "-y", "install", "curl", "jq", "zip"]
- name: 'ubuntu'
  args: ["zip", "-r", "extension.zip", "extension"]

#decrypt
- name: gcr.io/cloud-builders/gcloud
  args: ["kms", "decrypt", "--ciphertext-file=secrets.json.enc", "--plaintext-file=secrets.json", "--location=global", "--keyring=foxslash-keyring", "--key=foxslash-apps"]

#secret variables
- name: 'ubuntu'
  args: ["CLIENT_SECRET=$(cat", "secrets.json", "|", "jq", "-r", ".clientSecret)"]
- name: 'ubuntu'
  args: ["REFRESH_TOKEN=$(cat secrets.json | jq -r .refreshToken)"]
- name: 'ubuntu'
  args: ["JWT_SECRET=$(cat secrets.json | jq -r .jwtSecret)"]

#Chrome Webstore
- name: 'ubuntu'
  args: ["ACCESS_TOKEN=$(curl 'https://accounts.google.com/o/oauth2/token' -d 'client_id=${_CLIENT_ID}&client_secret=$CLIENT_SECRET&refresh_token=$REFRESH_TOKEN&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob | jq -r .access_token)"]
- name: 'ubuntu'
  args: ["curl -H 'Authorization: Bearer $ACCESS_TOKEN' -H 'x-goog-api-version: 2' -X PUT -T extension.zip -v 'https://www.googleapis.com/upload/chromewebstore/v1.1/items/${_APP_ID}'"]
  #curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T pointless.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${_APP_ID}"
- name: 'ubuntu'
  args: ["curl -H 'Authorization: Bearer $ACCESS_TOKEN' -H 'x-goog-api-version: 2' -H 'Content-Length: 0' -X POST -v 'https://www.googleapis.com/chromewebstore/v1.1/items/${_APP_ID}/publish'"]
  #curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${_APP_ID}/publish"

#Mozilla Add-ons
- name: 'ubuntu'
  args: ["EXTENSION_VERSION=$(cat test.json | jq -r '.version')"]
- name: 'ubuntu'
  args: ["curl 'https://addons.mozilla.org/api/v4/addons/' -g -XPOST -F 'upload=@extension.zip' -F 'version=$EXTENSION_VERSION' -H 'Authorization: JWT $JWT_SECRET'"]

substitutions:
    _CLIENT_ID: 487050059648-4iej3hk4mbbhdravaaake8vs72s2cdi2.apps.googleusercontent.com
    _APP_ID: eopegaefgepfdedhecfbclehhffiebpk

options:
    substitution_option: 'ALLOW_LOOSE'