name: Predeploy Steps
on:
  pull_request:
    branches:
      - main
      - beta
jobs:
  version_and_build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Bun dependencies
        run: bun install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Get Automated Version Number
        id: version_check
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: echo ::set-output name=version::$(bunx semantic-release --dry-run | grep 'The next release version is' | sed -E 's/.*The next release version is (.+)$/\1/')

      - name: Output Version Number
        id: version
        run: |
          if [ '${{steps.version_check.outputs.version}}' == '' ]
          then
              echo "::set-output name=version::'0.0.0'"
          else
              echo "::set-output name=version::'${{steps.version_check.outputs.version}}'"
          fi

      - name: Test Build Project
        run: bun run build

      - name: Automated Versioning and Release
        if: ${{ steps.version.outputs.version != '' }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: bunx semantic-release

      - name: Zip Folder
        run: cd dist && zip -r ../extension.zip *

      - name: Save files to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension
          path: |
            extension.zip
